### ISSUE TITLE
Modelar Tabelas: Usuário do Sistema e Grupos de Permissão

### ISSUE THREAD

**Issue by NicSouza** [projetoKhali/api5back#59]
### Descrição

Desenvolver as tabelas para gerenciamento de usuários do sistema e grupos de permissão, com o objetivo de permitir um controle de acesso seguro e configurável para a aplicação. A modelagem deve possibilitar que cada usuário seja associado a um grupo de permissão.

### Escopo

- Modelagem da tabela Usuário do Sistema
- Modelagem da tabela Grupos de Permissão 
- Criação de uma tabela de relacionamento entre Usuários do Sistema e Grupos de Permissão para gerenciar associações

### Critérios de Aceitação

- As tabelas devem estar modeladas e configuradas no banco de dados

### Pontos de Teste

- Testar a criação de um novo usuário e associá-lo a um grupo de permissão, garantindo que os dados são corretamente vinculados
- Tentar associar um usuário a um grupo inexistente e verificar se o sistema impede essa ação.

### Dependências

- [ ] Depende de outra issue
- [ ] Impacta outras issues

**Comment by Incivius** [comment]
![image](https://github.com/user-attachments/assets/1c2b6a65-94bf-45ec-9ef8-373398db7f78)


Segue modelo da novas tabelas
